### ISSUE TITLE
hi it doesn't work

### ISSUE THREAD

**Issue by slince** [multidimension-al/cakephp-subdomains#16]
Hello

This is my code.
//routes.php
![image](https://cloud.githubusercontent.com/assets/3785826/21843785/389036be-d827-11e6-9f7f-0876ecc8918d.png)

I'have create a /config/subdomain.php ;like 
![image](https://cloud.githubusercontent.com/assets/3785826/21843841/6d26c280-d827-11e6-8596-15fc08b06ed6.png)

//bootstrap.php
```
Plugin::load('Multidimensional/Subdomains', ['bootstrap' => true, 'routes' => true]);
```
When i visit www.domain.com and supplier.domain.com; they all match home page.  What's wrong with me?

**Comment by ajquick** [comment]
Hello,

You shouldn't need to create the fallback inside your route.php file, that will be done automatically in the plugin. All fallbacks should be generated last (after the Plugin::routes() command), which will help link together all the routes you have already created.

You may also want to try adding the routeClass to your route:

```php
['routeClass' => 'Multidimensional/Subdomains.SubdomainRoute']
```
